'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.FeedbackCenter

    Partial Public Class EditProducts

        '''<summary>
        '''plParentCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plParentCategory As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpParentCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpParentCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plChildCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plChildCategories As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblNoCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoCategories As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSortOrder As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lstChildCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstChildCategories As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''lblCategoryUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategoryUpdated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblActions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdEdit As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hbtnEditHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hbtnEditHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmdView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdView As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hbtnViewHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hbtnViewHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmdAddNewProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddNewProduct As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
