'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.FeedbackCenter

    Partial Public Class LatestOptions

        '''<summary>
        '''tblLatestCommentsDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblLatestCommentsDetail As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plFeedbackCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFeedbackCount As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFeedbackCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFeedbackCount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCount As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valCountType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCountType As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plQueryStringFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plQueryStringFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkQueryStringFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkQueryStringFilter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plQueryStringParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plQueryStringParam As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtQueryStringParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQueryStringParam As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplate As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plHtmlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlBody As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlBody As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlFooter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHtmlNoFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHtmlNoFeedback As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHtmlNoFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHtmlNoFeedback As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTokens As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTokens As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProduct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVoteTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVoteTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVoteTotalNegative control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVoteTotalNegative As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
