'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.FeedbackCenter

    Partial Public Class Settings

        '''<summary>
        '''plEmailNotification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailNotification As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailNotification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailNotification As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEnableCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableCaptcha As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableCaptcha As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableRSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableRSS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEnableStatistics control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableStatistics As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableStatistics control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableStatistics As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCommentAttachments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCommentAttachments As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkCommentAttachments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCommentAttachments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshActiveSocial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshActiveSocial As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblActiveSocial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblActiveSocial As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plActiveSocialSubmissionKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plActiveSocialSubmissionKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtActiveSocialSubmissionKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActiveSocialSubmissionKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plActiveSocialSubscribeKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plActiveSocialSubscribeKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtActiveSocialSubscribeKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActiveSocialSubscribeKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plActiveSocialVoteKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plActiveSocialVoteKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtActiveSocialVoteKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActiveSocialVoteKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plActiveSocialCommentKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plActiveSocialCommentKey As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtActiveSocialCommentKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActiveSocialCommentKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSecurity As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSecurity As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPermissions As Global.System.Web.UI.UserControl

        '''<summary>
        '''grdPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPermissions As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
