'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.FeedbackCenter.Controls

    Partial Public Class PostComment

        '''<summary>
        '''pnlPostComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPostComment As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valComment As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''phAnonymousUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phAnonymousUser As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valEmailIsValid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailIsValid As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''txtURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtURL As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUrl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phAttachment As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''txtCommentAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCommentAttachment As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''lblAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAttachment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCaptcha As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ctlCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlCaptcha As Global.DotNetNuke.UI.WebControls.CaptchaControl

        '''<summary>
        '''btnPostComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPostComment As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblPostCommentNotAuthorized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostCommentNotAuthorized As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
